export const EZ_IMPORT_URL = "https://entropyzero.vercel.app";

export const LIFE_PHASES = [
  { id: "early_childhood", label: "Early childhood", sub: "age 0–6",   emoji: "🧸", ageStart: 0,  ageEnd: 6   },
  { id: "primary_school",  label: "Primary school",  sub: "age 6–11",  emoji: "📚", ageStart: 6,  ageEnd: 11  },
  { id: "middle_school",   label: "Middle school",   sub: "age 11–14", emoji: "🎒", ageStart: 11, ageEnd: 14  },
  { id: "high_school",     label: "High school",     sub: "age 14–18", emoji: "🏫", ageStart: 14, ageEnd: 18  },
  { id: "college",         label: "College / Uni",   sub: "age 18–22", emoji: "🎓", ageStart: 18, ageEnd: 22  },
  { id: "early_career",    label: "Early career",    sub: "age 22–27", emoji: "💼", ageStart: 22, ageEnd: 27  },
  { id: "mid_career",      label: "Mid career",      sub: "age 27–35", emoji: "📈", ageStart: 27, ageEnd: 35  },
  { id: "established",     label: "Established",     sub: "age 35+",   emoji: "🏛", ageStart: 35, ageEnd: 100 },
];

export const PHASE_QUESTIONS = {
  early_childhood: [
    { id: "family_stability", label: "Family stability",     type: "range", min: -5, max: 5, help: "Stable loving home → +5. Turbulent / absent parents → -5." },
    { id: "health",           label: "Health",               type: "range", min: -3, max: 3, help: "Major illness → -3. Perfectly healthy → +3." },
    { id: "key_events",       label: "Key events",           type: "chips",  options: ["Parents divorced","Moved cities","New sibling","Financial hardship","Bereavement","Abuse/trauma","Immigrated","Very happy childhood"] },
    { id: "narrative",        label: "Describe this phase",  type: "text" },
  ],
  primary_school: [
    { id: "academics",  label: "Academic performance",      type: "range", min: -4, max: 4 },
    { id: "social",     label: "Social life & friendships", type: "range", min: -3, max: 3 },
    { id: "confidence", label: "Self-confidence",           type: "range", min: -3, max: 3 },
    { id: "key_events", label: "Key events",                type: "chips",  options: ["Bullied","Won competition","Found a passion","Family crisis","Best years of childhood","Changed schools","Learned instrument/sport"] },
    { id: "narrative",  label: "Describe this phase",       type: "text" },
  ],
  middle_school: [
    { id: "academics",  label: "Academics",                  type: "range", min: -4, max: 4 },
    { id: "social",     label: "Social / friendships",       type: "range", min: -4, max: 4 },
    { id: "identity",   label: "Identity & self-discovery",  type: "range", min: -3, max: 3, help: "Confused/lost → -3. Clear sense of self → +3." },
    { id: "key_events", label: "Key events",                 type: "chips",  options: ["First relationship","Family problems","Moved schools","Discovered passion","Mental health struggles","Bullied","Excelled in sport/art","Big failure"] },
    { id: "narrative",  label: "Describe this phase",        type: "text" },
  ],
  high_school: [
    { id: "academics",     label: "Academic performance",    type: "range", min: -5, max: 5, help: "Board result influence." },
    { id: "social",        label: "Social life",             type: "range", min: -4, max: 4 },
    { id: "mental_health", label: "Mental health",           type: "range", min: -5, max: 5 },
    { id: "relationships", label: "Romantic life",           type: "range", min: -3, max: 3 },
    { id: "key_events",    label: "Key events",              type: "chips",  options: ["First heartbreak","Board exam failure","Board exam success","Parental pressure","Lost a friend","Discovered ambition","Substance use","Part-time job","Won big competition","Mental health crisis"] },
    { id: "narrative",     label: "Describe this phase",     type: "text" },
  ],
  college: [
    { id: "academics",     label: "Academic performance",    type: "range", min: -5, max: 5 },
    { id: "social",        label: "Social & friendships",    type: "range", min: -4, max: 4 },
    { id: "mental_health", label: "Mental health",           type: "range", min: -5, max: 5 },
    { id: "relationships", label: "Romantic relationships",  type: "range", min: -4, max: 4 },
    { id: "finances",      label: "Financial situation",     type: "range", min: -3, max: 3 },
    { id: "key_events",    label: "Key events",              type: "chips",  options: ["Dropped out","Changed degree","Serious relationship","Heartbreak","Internship","Founded something","Mental breakdown","Got into dream college","Missed dream college","Financial crisis","Lost parent/close person","Studied abroad"] },
    { id: "narrative",     label: "Describe this phase",     type: "text" },
  ],
  early_career: [
    { id: "career",        label: "Career trajectory",       type: "range", min: -5, max: 5 },
    { id: "finances",      label: "Financial stability",     type: "range", min: -5, max: 5 },
    { id: "relationships", label: "Relationships / love",    type: "range", min: -5, max: 5 },
    { id: "mental_health", label: "Mental health",           type: "range", min: -5, max: 5 },
    { id: "purpose",       label: "Sense of direction",      type: "range", min: -4, max: 4, help: "Feeling lost → -4. Clear goals → +4." },
    { id: "key_events",    label: "Key events",              type: "chips",  options: ["Got fired","Big promotion","Started company","Marriage","Breakup","Moved country","Debt crisis","Mental health crisis","Found dream job","Lost a parent","Had a child","Huge financial win"] },
    { id: "narrative",     label: "Describe this phase",     type: "text" },
  ],
  mid_career: [
    { id: "career",        label: "Career peak vs plateau",  type: "range", min: -5, max: 5 },
    { id: "finances",      label: "Financial stability",     type: "range", min: -5, max: 5 },
    { id: "relationships", label: "Family / relationships",  type: "range", min: -5, max: 5 },
    { id: "health",        label: "Physical & mental health",type: "range", min: -5, max: 5 },
    { id: "purpose",       label: "Sense of meaning",        type: "range", min: -5, max: 5 },
    { id: "key_events",    label: "Key events",              type: "chips",  options: ["Career plateau","Major achievement","Divorce","Second marriage","Business failure","Health scare","Big exit/win","Lost job","Started over","Midlife crisis","Major investment/property"] },
    { id: "narrative",     label: "Describe this phase",     type: "text" },
  ],
  established: [
    { id: "career",        label: "Career / legacy",         type: "range", min: -5, max: 5 },
    { id: "finances",      label: "Financial security",      type: "range", min: -5, max: 5 },
    { id: "relationships", label: "Relationships & family",  type: "range", min: -5, max: 5 },
    { id: "health",        label: "Health trajectory",       type: "range", min: -5, max: 5 },
    { id: "purpose",       label: "Sense of fulfillment",    type: "range", min: -5, max: 5 },
    { id: "key_events",    label: "Key events",              type: "chips",  options: ["Retirement","Health crisis","Wealth built","Family estrangement","Grandchildren","Career reinvention","Philanthropy","Loss of partner"] },
    { id: "narrative",     label: "Describe this phase",     type: "text" },
  ],
};

export const EVENT_IMPACTS = {
  "Parents divorced": -8,    "Family crisis": -7,       "Financial hardship": -6,
  "Bereavement": -9,         "Abuse/trauma": -10,       "Immigrated": -3,
  "Very happy childhood": 7, "New sibling": 2,          "Moved cities": -2,
  "Bullied": -7,             "Won competition": 6,      "Found a passion": 8,
  "Changed schools": -3,     "Learned instrument/sport": 5,
  "First relationship": 4,   "Excelled in sport/art": 6,"Big failure": -7,
  "Mental health struggles": -8, "First heartbreak": -6,"Board exam failure": -7,
  "Board exam success": 8,   "Parental pressure": -4,   "Lost a friend": -5,
  "Discovered ambition": 7,  "Substance use": -5,       "Part-time job": 3,
  "Won big competition": 8,  "Mental health crisis": -9,
  "Dropped out": -5,         "Changed degree": -2,      "Serious relationship": 5,
  "Heartbreak": -6,          "Internship": 4,           "Founded something": 8,
  "Mental breakdown": -10,   "Got into dream college": 9,"Missed dream college": -8,
  "Financial crisis": -8,    "Lost parent/close person": -10, "Studied abroad": 6,
  "Got fired": -8,           "Big promotion": 8,        "Started company": 6,
  "Marriage": 7,             "Breakup": -7,             "Moved country": -3,
  "Debt crisis": -8,         "Found dream job": 9,      "Had a child": 6,
  "Huge financial win": 9,   "Career plateau": -4,      "Major achievement": 9,
  "Divorce": -9,             "Second marriage": 5,      "Business failure": -9,
  "Health scare": -7,        "Big exit/win": 10,        "Lost job": -8,
  "Started over": -5,        "Midlife crisis": -6,      "Major investment/property": 6,
  "Retirement": 3,           "Health crisis": -8,       "Wealth built": 9,
  "Family estrangement": -7, "Grandchildren": 6,        "Career reinvention": 5,
  "Philanthropy": 4,         "Loss of partner": -10,
};
